youtube:
  # Your google API key here
  apiKey:

  # Your video id goes here
  videoId:

  # Delay before new message is received from YouTube
  # This number is in seconds
  messageDelay: 5


port:
  # Port used for the server
  backend: 8080

  # Port used for the browser
  frontend: 3000


aspectRatio:
  width: 1920
  height: 1080

  # Images larger than 1920x1080 are scaled down to 1920x1080 and then
  # scaled further down to prevent emotes from going out of view when at the edge

  scale: 0.9

  # Emote sizes
  emote:
    width: 50
    height: 50

testing:
  # show emotes to see an example of how this program works
  # true = yes to test
  # false = false to test
  test: false

  # How long to wait before the next emote pops up on the screen during a test
  # A lower number means the emotes pop up faster
  # This number is in seconds
  speedOfEmotes: 0.5