youtube:
  # Your google API key here
  apiKey:

  # Your video id goes here
  videoId:

  # Delay before new message is received from YouTube
  # This number is in seconds
  messageDelay: 5

# ------------------------------------------------------------------------------

# Port to be used by the app
port: 3124

# ------------------------------------------------------------------------------

aspectRatio:
  # Force images that are larger than [width x height] to scale down to fit
  forceWidthHeight: true
  width: 1920
  height: 1080

  # Not used but in code, leave at 1
  scaleCanvas: 1

  # Not used but in code, leave at 1
  scaleImage: 1

# ------------------------------------------------------------------------------

emote:
  # Width and height of the emote images
  # Width and height should be the same for now
  width: 50
  height: 50

  # Increase or decrease emote size by up to the number below
  randomSizeIncrease: 10
  randomSizeDecrease: 10

  # The max amount of emotes displayed before the oldest one is removed
  maxEmoteCount: 200

  # Add rounded edges around the emote. Emotes will be cut off at the edges
  # 0 leaves the emote alone
  # 50 turns the emote into a circle
  # Anything higher than 50 defaults to 50
  roundness: 0

  # Add a background color to the transparent parts of an emote.
  # Can use RGBA or Hex with alpha
  # rgba(255, 255, 255, 0) and #FFFFFF00 are transparent
  backgroundColor: "rgba(255, 255, 255, 0)"

# ------------------------------------------------------------------------------

testing:
  # Meant for testing but can be used instead of connecting to youtube
  # Displays random emotes from emotes folder
  # true = yes to test
  # false = false to test, will connect to youtube
  test: true

  # How long to wait before the next emote pops up on the screen
  # Only affects the speed during a test
  # A lower number means the emotes pop up faster
  # This number is in milliseconds
  speedOfEmotes: 1000
