youtube:
  # Your google API key here
  apiKey: AIzaSyAxOjESchGSZKbX4bgXOI9RWLno8YnFERA

  # Your video id goes here
  videoId: 

  # Delay before new message is received from YouTube
  # This number is in seconds
  messageDelay: 5

# ------------------------------------------------------------------------------

# Port to be used by the app Default = 3124
# Changing this will still work with the browser but the Windows window will be empty
port: 3124

# ------------------------------------------------------------------------------

# Have not tested changing this
aspectRatio:
  width: 1920
  height: 1080

  # Images larger than 1920x1080 are scaled down to 1920x1080 and then
  # scaled further down to prevent emotes from going out of view when at the edge
  scaleCanvas: 0.9

  # Images will not scale higher than 1920x1080
  # Scaling includes the transparent parts as well
  scaleImage: 1

  # Emote sizes
  # Should be set the same for both width and height
  # width = height

# ------------------------------------------------------------------------------

emote:
  width: 50
  height: 50

  # Increase or decrease emote size by up to the number below
  randomSizeIncrease: 10
  randomSizeDecrease: 10

  # The max amount of emotes displayed before the oldest one is removed
  maxEmoteCount: 200

  # Add rounded edges around the emote. Emotes will be cut off at the edges
  # 0 leaves the emote alone
  # 50 turns the emote into a circle
  # Anythign higher than 50 defaults to 50
  roundness: 0

  # Add a background color to the transparent parts of an emote.
  # Can use RGBA or Hex with alpha
  # rgba(255, 255, 255, 0) and #FFFFFF00 are transparent
  backgroundColor: "rgba(255, 255, 255, 0)"

# ------------------------------------------------------------------------------

testing:
  # show emotes to see an example of how this program works
  # true = yes to test
  # false = false to test
  test: true

  # How long to wait before the next emote pops up on the screen during a test
  # A lower number means the emotes pop up faster
  # This number is in milliseconds
  speedOfEmotes: 1000
