youtube:
  apiKey: 
  videoId: 
  messageDelay: 50
port: 3124
aspectRatio:
  forceWidthHeight: true
  width: 1920
  height: 1080
  scaleCanvas: 1
  scaleImage: 1
emote:
  width: 50
  height: 0
  randomSizeIncrease: 10
  randomSizeDecrease: 7
  maxEmoteCount: 200
  roundness: 0
  backgroundColor: rgba(255, 255, 255, 0)
testing:
  test: true
  speedOfEmotes: 6500
